### PR TITLE
Z3: 4.5.0.post2 -> 4.7.1.post1

### LINKED ISSUE #7: z3-solver package on Python package index doesn't include Python 3 wheels
https://pypi.python.org/pypi/z3-solver

The `z3-solver` package only has Python 2 wheels, but I expect it to have Python 3 wheels as well, since the documentation seems to suggest that there is Python 3 support.

(I was directed here by https://github.com/Z3Prover/z3/issues/1254#issuecomment-329397358.)

### PR DESCRIPTION
**Pull request by Mic92**
Updates 2 years old version of z3. Changelog does not list breaking changes: https://github.com/Z3Prover/z3/blob/master/RELEASE_NOTES#L36 - we also did not had any issues upgrading other z3 projects in nixpkgs.
Motivation: Older version does no longer compile with newer versions of gcc.

Maybe you also want to upload a wheel version for python3 this time to fix: https://github.com/angr/angr-z3/issues/7

This pull request is the result of `git rebase` of your old master onto 4.7.1. I only changed the version number here: https://github.com/Mic92/z3/commit/a20a1939168dd933184f01946e5b614deb7dc63e#diff-1523b20a37fbe9727189fa6bd83a0936R175
You can either create a new branch for this or force push my changes.

### CODE REVIEW

**Comment by rhelmot** [comment]
Sorry for letting this rot - I've gone ahead and done the upgrade to 4.8.0 myself, and I'm gonna be trying to upstream my changes so this repo can die for real.

**Comment by Mic92** [comment]
Can you create a new tag on master, so we can update claripy as well?

**Comment by rhelmot** [comment]
I’m not sure I understand the question, since git tags don’t factor into any angr release process I know of, but there are breaking API changes preventing claripy from being updated. See angr/claripy#86.

**Comment by Mic92** [comment]
True, a pypi release would make more sense.

**Comment by rhelmot** [comment]
The new pypi release is out there...

**Comment by Mic92** [comment]
alright then.

**Pull request closed without merging**
